function u = step1matrix_solver(mu, lambda1, lambda2, A, m, n, rhs)
% Generates the solver from step1matrix.m and solve_Laplace.m to be 
% used in Split Bregman. 
% inputs:
% mu, lambda1, lambda2 are constants that depend on the data scale
% A is the matrix generated by the robot (or simulated paths)
% m and n are the dimensions of u and m*n should be the number of columns in A
% rhs = some function of g, A, etc.
% output: the reconstructed image u as a vector

% depends on step1matrix.m, solve_Laplace.m
	% disp('step1matrix_solver start')
	% keyboard
	step1 = @(u) step1matrix(mu, lambda1, lambda2, A, u, m, n);
	tol = 10e-8;
	max_iter = 1000;
	preconditioner = @(f) solve_Laplace(f, lambda1, lambda2, m, n);
	[u flag] = pcg(step1, rhs, tol, max_iter, preconditioner);
end
